apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
      - name: flask-frontend
        image: docker.io/sk65/flask-frontend:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

